#pragma once

#ifndef MINECRAFT_VERSION_DEFINITIONS_
#define MINECRAFT_VERSION_DEFINITIONS_

#define MINECRAFT_RAKNET_PROTOCOL_VERSION 11
#define MINECRAFT_PROTOCOL_VERSION 589
#define MINECRAFT_VERSION "1.20.0"

#endif
