#pragma once

enum NbtTagDefinitions
{
	ID_TAG_END,
	ID_TAG_INT8,
	ID_TAG_INT16,
	ID_TAG_INT32,
	ID_TAG_INT64,
	ID_TAG_FLOAT,
	ID_TAG_DOUBLE,
	ID_TAG_INT8_ARRAY,
	ID_TAG_STRING,
	ID_TAG_LIST,
	ID_TAG_COMPOUND,
	ID_TAG_INT32_ARRAY,
	ID_TAG_INT64_ARRAY
};