#pragma once

enum PacketDefinitions
{
	ID_NONE,
	ID_LOGIN,
	ID_PLAY_STATUS,
	ID_RESOURCE_PACKS_INFO = 0x06,
	ID_RESOURCE_PACK_STACK,
	ID_RESOURCE_PACK_CLIENT_RESPONSE,
	ID_START_GAME = 0x0b,
	ID_BIOME_DEFINITION_LIST = 0x7a,
	ID_NETWORK_SETTINGS = 0x8f,
	ID_CREATIVE_CONTENT = 0x91,
	ID_REQUEST_NETWORK_SETTINGS = 0xc1,
	ID_GAME = 0xFE
};